name: Publish release

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Ezzatron
    uses: ezzatron/repos/.github/workflows/shared-publish-release.yml@main
    secrets: inherit
    permissions:
      contents: write
      discussions: write
    with:
      discussionCategory: Releases
      tag: ${{ github.ref_name }}
