name: Publish package

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  ci:
    name: Ezzatron
    uses: ezzatron/repos/.github/workflows/shared-publish-package-npm.yml@main
    secrets: inherit
    permissions:
      id-token: write
